### ISSUE TITLE
Pentaho BA 6.1.0.1 Language Pack Installer - Couldn't find field 'rawData' in row!

### ISSUE THREAD

**Issue by marucan** [webdetails/pentahoLanguagePacks#122]
Attempted to install "Arabic" Language Pack Installer for Pentaho BA 6.1.0.1. and received the following error in the pentaho.log file.  Can you please advise?

From pentaho.log file:
2016-06-01 14:18:49,439 INFO  [pt.webdetails.cpk.elements.impl.KettleJobElement] Starting job 'installpack' (installPack)
2016-06-01 14:18:49,557 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - installPack - Start of job execution
2016-06-01 14:18:49,584 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - installPack - Starting entry [Write To Log]
2016-06-01 14:18:49,599 INFO  [org.pentaho.di] 2016/06/01 14:18:49 -  - Installpack: 
cpk.webapp.dir = /C:/pentaho/server/biserver-ee/tomcat/webapps/pentaho/
cpk.solution.system.dir = /C:/pentaho/server/biserver-ee/pentaho-solutions/system/
cpk.solution.dir = ${cpk.solution.dir}
cpk.webapp.dir = /C:/pentaho/server/biserver-ee/tomcat/webapps/pentaho/
cpk.plugin.dir = /C:/pentaho/server/biserver-ee/pentaho-solutions/system/languagePackInstaller/
2016-06-01 14:18:49,599 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - installPack - Starting entry [get pack metadata]
2016-06-01 14:18:49,608 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - get pack metadata - Loading transformation from XML file [file:///C:/pentaho/server/biserver-ee/pentaho-solutions/system/languagePackInstaller/endpoints/kettle/admin/getpackmetadata.ktr]
2016-06-01 14:18:49,609 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
2016-06-01 14:18:49,692 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
2016-06-01 14:18:49,718 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
2016-06-01 14:18:49,720 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - get pack metadata - Dispatching started for transformation [get pack metadata]
2016-06-01 14:18:49,761 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
2016-06-01 14:18:49,762 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - Load utf8 file content in memory.0 - Finished processing (I=1, O=0, R=0, W=1, U=0, E=0)
2016-06-01 14:18:49,782 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - Set Variables.0 - Setting environment variables...
2016-06-01 14:18:49,788 ERROR [org.pentaho.di] 2016/06/01 14:18:49 - Select values.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Couldn't find field 'rawData' in row!
2016-06-01 14:18:49,788 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - Select values.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)
2016-06-01 14:18:49,797 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - Write to log.0 - 
2016/06/01 14:18:49 - Write to log.0 - ------------> Linenr 1------------------------------
2016/06/01 14:18:49 - Write to log.0 - Injected variables: 
cpk.webapp.dir = /C:/pentaho/server/biserver-ee/tomcat/webapps/pentaho/
cpk.plugin.dir = /C:/pentaho/server/biserver-ee/pentaho-solutions/system/languagePackInstaller/
2016/06/01 14:18:49 - Write to log.0 - 
2016/06/01 14:18:49 - Write to log.0 - File content = {
    "appTitle": "Arabic Language Pack Installer",
    "appWelcomeMessage": "This plugin installs language definitions for the Arabic language in Pentaho",
    "language": "???????",
    "languageCode": "ar",
    "pentahoVersion": "6.0.0",
    "maturity": {
        "lane": "Community",
        "phase": "2"
    },
    "maintainer": {
        "name": "",
        "email": "",
        "img": "",
        "url": ""
    },
    "credits": [{
        "name": "",
        "email": "",
        "img": "",
        "url": ""
    }],
    "sponsors": [{
        "name": "",
        "email": "",
        "img": "",
        "url": ""
    }]
}

2016/06/01 14:18:49 - Write to log.0 - 
2016/06/01 14:18:49 - Write to log.0 - ====================
2016-06-01 14:18:49,797 ERROR [org.pentaho.di] 2016/06/01 14:18:49 - Set Variables.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Unexpected error
2016-06-01 14:18:49,797 ERROR [org.pentaho.di] 2016/06/01 14:18:49 - Set Variables.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2016/06/01 14:18:49 - Set Variables.0 - Unable to find field [language] in input row
2016/06/01 14:18:49 - Set Variables.0 - 
2016/06/01 14:18:49 - Set Variables.0 - 	at org.pentaho.di.trans.steps.setvariable.SetVariable.setValue(SetVariable.java:109)
2016/06/01 14:18:49 - Set Variables.0 - 	at org.pentaho.di.trans.steps.setvariable.SetVariable.processRow(SetVariable.java:89)
2016/06/01 14:18:49 - Set Variables.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2016/06/01 14:18:49 - Set Variables.0 - 	at java.lang.Thread.run(Thread.java:745)
2016-06-01 14:18:49,824 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - Set Variables.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)
2016-06-01 14:18:49,824 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - Write to log.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=0)
2016-06-01 14:18:49,831 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - get pack metadata - Transformation detected one or more steps with errors.
2016-06-01 14:18:49,831 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - get pack metadata - Transformation is killing the other steps!
2016-06-01 14:18:49,833 ERROR [org.pentaho.di] 2016/06/01 14:18:49 - get pack metadata - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Errors detected!
2016-06-01 14:18:49,834 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - import metadata.json.0 - Finished processing (I=0, O=0, R=1, W=3, U=0, E=0)
2016-06-01 14:18:49,959 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - get pack metadata - Transformation detected one or more steps with errors.
2016-06-01 14:18:49,959 ERROR [org.pentaho.di] 2016/06/01 14:18:49 - get pack metadata - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Errors detected!
2016-06-01 14:18:49,959 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - get pack metadata - Transformation is killing the other steps!
2016-06-01 14:18:49,961 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - installPack - Starting entry [File Exists]
2016-06-01 14:18:49,961 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - installPack - Starting entry [Abort job]
2016-06-01 14:18:49,961 ERROR [org.pentaho.di] 2016/06/01 14:18:49 - Abort job - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Aborting job.
2016-06-01 14:18:49,961 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - installPack - Finished job entry [Abort job] (result=[false])
2016-06-01 14:18:49,961 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - installPack - Finished job entry [File Exists] (result=[false])
2016-06-01 14:18:49,961 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - installPack - Finished job entry [get pack metadata] (result=[false])
2016-06-01 14:18:49,961 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - installPack - Finished job entry [Write To Log] (result=[false])
2016-06-01 14:18:49,961 INFO  [org.pentaho.di] 2016/06/01 14:18:49 - installPack - Job execution finished
2016-06-01 14:18:49,987 INFO  [pt.webdetails.cpk.elements.impl.KettleJobElement] Finished job 'installpack' (installPack) in 548 ms
2016-06-01 14:18:50,002 INFO  [pt.webdetails.cpk.elements.impl.KettleJobElement] [ pt.webdetails.cpk.elements.impl.KettleResult@2bdddddb ]

**Comment by carlosrusso** [comment]
Hello

The Arabic package contains an error, that could be related with unicode conversion.
 Try to edit the file metadata.json,  changing  line 4 from:

`"language": "العربية",`

to

` "language": "Arabic",`

Lets us know how it went.

**Comment by marucan** [comment]
Thank you for the response.  I updated the json file and received the following error message in the log file:

2016/06/07 15:13:48 - Select values.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Couldn't find field 'rawData' in row!
org.pentaho.di.core.exception.KettleException: 
Unable to find field [language] in input row

2016/06/07 15:14:51 - Select values.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Couldn't find field 'rawData' in row!
	at org.pentaho.di.trans.steps.setvariable.SetVariable.setValue(SetVariable.java:109)
	at org.pentaho.di.trans.steps.setvariable.SetVariable.processRow(SetVariable.java:89)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
	at java.lang.Thread.run(Unknown Source)
2016/06/07 15:14:51 - get pack metadata - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Errors detected!
2016/06/07 15:14:51 - Set Variables.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Unexpected error
2016/06/07 15:14:51 - Set Variables.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2016/06/07 15:14:51 - Set Variables.0 - Unable to find field [language] in input row
2016/06/07 15:14:51 - Set Variables.0 - 
2016/06/07 15:14:51 - Set Variables.0 - 	at org.pentaho.di.trans.steps.setvariable.SetVariable.setValue(SetVariable.java:109)
2016/06/07 15:14:51 - Set Variables.0 - 	at org.pentaho.di.trans.steps.setvariable.SetVariable.processRow(SetVariable.java:89)
2016/06/07 15:14:51 - Set Variables.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2016/06/07 15:14:51 - Set Variables.0 - 	at java.lang.Thread.run(Unknown Source)
2016/06/07 15:14:51 - get pack metadata - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Errors detected!
2016/06/07 15:14:51 - Abort job - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Aborting job.
org.pentaho.di.core.exception.KettleException: 

Please advise.  Thank you in advance.

**Comment by marucan** [comment]
Can anyone assist with this issue?  Tried various suggestions with no solution.  

Regards,
Michael

**Comment by carlosrusso** [comment]
Please download the pack http://ci.pentaho.com/job/webdetails-languagepackinstallers-trunk/58/artifact/dist/languagePack_ar-6.1-SNAPSHOT.zip and attempt to use it. I think the problem is fixed now.

**Comment by matteoturra** [comment]
I have the same problem with the Italian LanguagePack.
08 Jul 2016 12:17:54,322 ERROR [org.pentaho.di] 2016/07/08 12:17:54 - Set Variables.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2016/07/08 12:17:54 - Set Variables.0 - Unable to find field [language] in input row
2016/07/08 12:17:54 - Set Variables.0 - 
2016/07/08 12:17:54 - Set Variables.0 - 	at org.pentaho.di.trans.steps.setvariable.SetVariable.setValue(SetVariable.java:109)
2016/07/08 12:17:54 - Set Variables.0 - 	at org.pentaho.di.trans.steps.setvariable.SetVariable.processRow(SetVariable.java:89)
2016/07/08 12:17:54 - Set Variables.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2016/07/08 12:17:54 - Set Variables.0 - 	at java.lang.Thread.run(Thread.java:745)

**Comment by oltibus** [comment]
Hello @carlosrusso . I'm having the same issue on installing the sq_AL language while getting it from github.com/oltibus/pentahoLanguagePacks

It doesn't happen while installing it on a pentaho that I get from Docker Hub (there it installs without any problem), while on a BISERVER 6.1 of mine, it says exactly like to @marucan
