### ISSUE TITLE
Error during install: - We can not find any data with path [$]!

### ISSUE THREAD

**Issue by matteoturra** [webdetails/pentahoLanguagePacks#125]
I follow the instruction to test my changes, but when I click on "install" button I got an error.

This is the pentaho.log 
'''
19 Aug 2016 17:24:50,424 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - installPack - Start of job execution
19 Aug 2016 17:24:50,428 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - installPack - Starting entry [Write To Log]
19 Aug 2016 17:24:50,430 INFO  [org.pentaho.di] 2016/08/19 17:24:50 -  - Installpack: 
2016/08/19 17:24:50 -  - cpk.webapp.dir = /var/lib/tomcat-pentaho/webapps/pentaho/
2016/08/19 17:24:50 -  - cpk.solution.system.dir = /production/pentaho/instances/pentaho/pentaho-solutions/system/
2016/08/19 17:24:50 -  - cpk.solution.dir = ${cpk.solution.dir}
2016/08/19 17:24:50 -  - cpk.webapp.dir = /var/lib/tomcat-pentaho/webapps/pentaho/
2016/08/19 17:24:50 -  - cpk.plugin.dir = /production/pentaho/instances/pentaho/pentaho-solutions/system/languagePackInstaller/
19 Aug 2016 17:24:50,430 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - installPack - Starting entry [get pack metadata]
19 Aug 2016 17:24:50,433 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - get pack metadata - Loading transformation from XML file [file:///production/pentaho/instances/pentaho/pentaho-solutions/system/languagePackInstaller/endpoints/kettle/admin/getpackmetadata.ktr]
19 Aug 2016 17:24:50,433 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
19 Aug 2016 17:24:50,436 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
19 Aug 2016 17:24:50,443 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
19 Aug 2016 17:24:50,444 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - get pack metadata - Dispatching started for transformation [get pack metadata]
19 Aug 2016 17:24:50,562 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
19 Aug 2016 17:24:50,564 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - Load utf8 file content in memory.0 - Finished processing (I=1, O=0, R=0, W=1, U=0, E=0)
19 Aug 2016 17:24:50,646 ERROR [org.pentaho.di] 2016/08/19 17:24:50 - import metadata.json.0 - ERROR (version 6.0.1.0-386, build 1 from 2015-12-03 11.37.25 by buildguy) : Unexpected Error : org.pentaho.di.core.exception.KettleException: 
2016/08/19 17:24:50 - import metadata.json.0 - org.pentaho.di.core.exception.KettleException: 
2016/08/19 17:24:50 - import metadata.json.0 - We can not find any data with path [$]!
2016/08/19 17:24:50 - import metadata.json.0 - 
2016/08/19 17:24:50 - import metadata.json.0 - 
2016/08/19 17:24:50 - import metadata.json.0 - We can not find any data with path [$]!
19 Aug 2016 17:24:50,647 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - Set Variables.0 - We didn't receive a row while setting the default values.
19 Aug 2016 17:24:50,647 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - Set Variables.0 - Finished after 0 rows.
19 Aug 2016 17:24:50,648 ERROR [org.pentaho.di] 2016/08/19 17:24:50 - import metadata.json.0 - ERROR (version 6.0.1.0-386, build 1 from 2015-12-03 11.37.25 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2016/08/19 17:24:50 - import metadata.json.0 - org.pentaho.di.core.exception.KettleException: 
2016/08/19 17:24:50 - import metadata.json.0 - We can not find any data with path [$]!
2016/08/19 17:24:50 - import metadata.json.0 - 
2016/08/19 17:24:50 - import metadata.json.0 - 
2016/08/19 17:24:50 - import metadata.json.0 - We can not find any data with path [$]!
2016/08/19 17:24:50 - import metadata.json.0 - 
2016/08/19 17:24:50 - import metadata.json.0 - 
2016/08/19 17:24:50 - import metadata.json.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonReader.getPath(JsonReader.java:191)
2016/08/19 17:24:50 - import metadata.json.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonInput.parseJson(JsonInput.java:281)
2016/08/19 17:24:50 - import metadata.json.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonInput.readFileOrString(JsonInput.java:258)
2016/08/19 17:24:50 - import metadata.json.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonInput.ReadNextString(JsonInput.java:165)
2016/08/19 17:24:50 - import metadata.json.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonInput.getOneRow(JsonInput.java:396)
2016/08/19 17:24:50 - import metadata.json.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonInput.processRow(JsonInput.java:344)
2016/08/19 17:24:50 - import metadata.json.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2016/08/19 17:24:50 - import metadata.json.0 - 	at java.lang.Thread.run(Thread.java:745)
2016/08/19 17:24:50 - import metadata.json.0 - Caused by: org.pentaho.di.core.exception.KettleException: 
2016/08/19 17:24:50 - import metadata.json.0 - We can not find any data with path [$]!
2016/08/19 17:24:50 - import metadata.json.0 - 
2016/08/19 17:24:50 - import metadata.json.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonReader.getPath(JsonReader.java:187)
2016/08/19 17:24:50 - import metadata.json.0 - 	... 7 more
19 Aug 2016 17:24:50,648 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - import metadata.json.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)
19 Aug 2016 17:24:50,649 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - get pack metadata - Transformation detected one or more steps with errors.
19 Aug 2016 17:24:50,649 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - get pack metadata - Transformation is killing the other steps!
19 Aug 2016 17:24:50,649 ERROR [org.pentaho.di] 2016/08/19 17:24:50 - get pack metadata - ERROR (version 6.0.1.0-386, build 1 from 2015-12-03 11.37.25 by buildguy) : Errors detected!
19 Aug 2016 17:24:50,651 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - installPack - Starting entry [File Exists]
19 Aug 2016 17:24:50,652 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - installPack - Starting entry [Abort job]
19 Aug 2016 17:24:50,653 ERROR [org.pentaho.di] 2016/08/19 17:24:50 - Abort job - ERROR (version 6.0.1.0-386, build 1 from 2015-12-03 11.37.25 by buildguy) : Aborting job.
19 Aug 2016 17:24:50,654 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - installPack - Finished job entry [Abort job] (result=[false])
19 Aug 2016 17:24:50,654 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - installPack - Finished job entry [File Exists] (result=[false])
19 Aug 2016 17:24:50,654 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - installPack - Finished job entry [get pack metadata] (result=[false])
19 Aug 2016 17:24:50,654 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - installPack - Finished job entry [Write To Log] (result=[false])
19 Aug 2016 17:24:50,654 INFO  [org.pentaho.di] 2016/08/19 17:24:50 - installPack - Job execution finished
'''

**Comment by matteoturra** [comment]
I still have thi isssue installing language pack on pentaho-BA 6.1.0.1

2016/09/06 18:11:26 - installPack - Start of job execution
2016/09/06 18:11:26 - installPack - Starting entry [Write To Log]
2016/09/06 18:11:26 -  - Installpack: 
2016/09/06 18:11:26 -  - cpk.webapp.dir = /var/lib/tomcat-pentaho/webapps/pentaho/
2016/09/06 18:11:26 -  - cpk.solution.system.dir = /production/pentaho/instances/pentaho/pentaho-solutions/system/
2016/09/06 18:11:26 -  - cpk.solution.dir = ${cpk.solution.dir}
2016/09/06 18:11:26 -  - cpk.webapp.dir = /var/lib/tomcat-pentaho/webapps/pentaho/
2016/09/06 18:11:26 -  - cpk.plugin.dir = /production/pentaho/instances/pentaho/pentaho-solutions/system/languagePack_sq_AL/
2016/09/06 18:11:26 - installPack - Starting entry [get pack metadata]
2016/09/06 18:11:26 - get pack metadata - Loading transformation from XML file [file:///production/pentaho/instances/pentaho/pentaho-solutions/system/languagePack_sq_AL/endpoints/kettle/admin/getpackmetadata.ktr]
2016/09/06 18:11:26 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
2016/09/06 18:11:26 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
2016/09/06 18:11:26 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
2016/09/06 18:11:26 - get pack metadata - Dispatching started for transformation [get pack metadata]
2016/09/06 18:11:26 - cfgbuilder - Warning: The configuration parameter [org] is not supported by the default configuration builder for scheme: sftp
2016/09/06 18:11:26 - Load utf8 file content in memory.0 - Finished processing (I=1, O=0, R=0, W=1, U=0, E=0)
2016/09/06 18:11:26 - Set Variables.0 - Setting environment variables...
org.pentaho.di.core.exception.KettleException: 
Unable to find field [language] in input row

	at org.pentaho.di.trans.steps.setvariable.SetVariable.setValue(SetVariable.java:109)
	at org.pentaho.di.trans.steps.setvariable.SetVariable.processRow(SetVariable.java:89)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
	at java.lang.Thread.run(Thread.java:745)
2016/09/06 18:11:26 - Write to log.0 - 
2016/09/06 18:11:26 - Write to log.0 - ------------> Linenr 1------------------------------
2016/09/06 18:11:26 - Write to log.0 - Injected variables: 
2016/09/06 18:11:26 - Write to log.0 - cpk.webapp.dir = /var/lib/tomcat-pentaho/webapps/pentaho/
2016/09/06 18:11:26 - Write to log.0 - cpk.plugin.dir = /production/pentaho/instances/pentaho/pentaho-solutions/system/languagePack_sq_AL/
2016/09/06 18:11:26 - Write to log.0 - 
2016/09/06 18:11:26 - Write to log.0 - File content = {
2016/09/06 18:11:26 - Write to log.0 -     "appTitle": "Paketë instalimi për gjuhën shqipe",
2016/09/06 18:11:26 - Write to log.0 -     "appWelcomeMessage": "Kjo paketë instalon përkthimet në gjuhën shqipe për Pentaho",
2016/09/06 18:11:26 - Write to log.0 -     "language": "Shqip",
2016/09/06 18:11:26 - Write to log.0 -     "languageCode": "sq_AL",
2016/09/06 18:11:26 - Write to log.0 -     "pentahoVersion": "6.0.1",
2016/09/06 18:11:26 - Write to log.0 -     "maturity": {
2016/09/06 18:11:26 - Write to log.0 -         "lane": "Community",
2016/09/06 18:11:26 - Write to log.0 -         "phase": "2"
2016/09/06 18:11:26 - Write to log.0 -     },
2016/09/06 18:11:26 - Write to log.0 -     "maintainer": {
2016/09/06 18:11:26 - Write to log.0 -         "name": "Olti Buzi",
2016/09/06 18:11:26 - Write to log.0 -         "email": "oltibuzi@gmail.com",
2016/09/06 18:11:26 - Write to log.0 -         "img": "",
2016/09/06 18:11:26 - Write to log.0 -         "url": "http:\/\/twitter.com\/oltimus"
2016/09/06 18:11:26 - Write to log.0 -     },
2016/09/06 18:11:26 - Write to log.0 -     "credits": [{
2016/09/06 18:11:26 - Write to log.0 -         "name": "",
2016/09/06 18:11:26 - Write to log.0 -         "email": "",
2016/09/06 18:11:26 - Write to log.0 -         "img": "",
2016/09/06 18:11:26 - Write to log.0 -         "url": ""
2016/09/06 18:11:26 - Write to log.0 -     }],
2016/09/06 18:11:26 - Write to log.0 -     "sponsors": [{
2016/09/06 18:11:26 - Write to log.0 -         "name": "",
2016/09/06 18:11:26 - Write to log.0 -         "email": "",
2016/09/06 18:11:26 - Write to log.0 -         "img": "",
2016/09/06 18:11:26 - Write to log.0 -         "url": ""
2016/09/06 18:11:26 - Write to log.0 -     }]
2016/09/06 18:11:26 - Write to log.0 - }
2016/09/06 18:11:26 - Write to log.0 - 
2016/09/06 18:11:26 - Write to log.0 - 
2016/09/06 18:11:26 - Write to log.0 - ====================
2016/09/06 18:11:26 - Select values.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Couldn't find field 'rawData' in row!
2016/09/06 18:11:26 - Set Variables.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Unexpected error
2016/09/06 18:11:26 - import metadata.json.0 - Finished processing (I=0, O=0, R=1, W=3, U=0, E=0)
child index = 3, logging object : org.pentaho.di.core.logging.LoggingObject@db96525 parent=a1751bb0-1e49-4945-993c-b36dd66b9dd3
2016/09/06 18:11:26 - Set Variables.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2016/09/06 18:11:26 - Set Variables.0 - Unable to find field [language] in input row
2016/09/06 18:11:26 - Set Variables.0 - 
2016/09/06 18:11:26 - Set Variables.0 - 	at org.pentaho.di.trans.steps.setvariable.SetVariable.setValue(SetVariable.java:109)
2016/09/06 18:11:26 - Set Variables.0 - 	at org.pentaho.di.trans.steps.setvariable.SetVariable.processRow(SetVariable.java:89)
2016/09/06 18:11:26 - Set Variables.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2016/09/06 18:11:26 - Set Variables.0 - 	at java.lang.Thread.run(Thread.java:745)
2016/09/06 18:11:26 - get pack metadata - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Errors detected!
2016/09/06 18:11:26 - Select values.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)
2016/09/06 18:11:26 - Write to log.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
2016/09/06 18:11:26 - Set Variables.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)
2016/09/06 18:11:26 - get pack metadata - Transformation detected one or more steps with errors.
2016/09/06 18:11:26 - get pack metadata - Transformation is killing the other steps!
2016/09/06 18:11:26 - get pack metadata - Transformation detected one or more steps with errors.
2016/09/06 18:11:26 - get pack metadata - Transformation is killing the other steps!
2016/09/06 18:11:26 - get pack metadata - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Errors detected!
2016/09/06 18:11:26 - installPack - Starting entry [File Exists]
2016/09/06 18:11:26 - installPack - Starting entry [Abort job]
2016/09/06 18:11:26 - Abort job - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Aborting job.
2016/09/06 18:11:26 - installPack - Finished job entry [Abort job] (result=[false])
2016/09/06 18:11:26 - installPack - Finished job entry [File Exists] (result=[false])
2016/09/06 18:11:26 - installPack - Finished job entry [get pack metadata] (result=[false])
2016/09/06 18:11:26 - installPack - Finished job entry [Write To Log] (result=[false])
2016/09/06 18:11:26 - installPack - Job execution finished
